version: "3.7"

services:
  bitcoin-regtest:
    image: freewil/bitcoin-testnet-box
    container_name: bitcoin-regtest
    restart: on-failure
    ports:
      - "127.0.0.1:19001:19001"
      - "127.0.0.1:19011:19011"
    command:
      - /home/tester/bitcoin-testnet-box/host/run.sh
    volumes:
      - ./data/run.sh:/home/tester/bitcoin-testnet-box/run.sh
      - ./data/1:/home/tester/bitcoin-testnet-box/1/regtest
      - ./data/2:/home/tester/bitcoin-testnet-box/2/regtest

  explorer1:
    image: msmiley/btc-rpc-explorer
    container_name: bitcoin-explorer-1
    restart: on-failure
    ports:
      - "127.0.0.1:8080:3002"
    environment:
      - "BTCEXP_BITCOIND_URI=bitcoin://admin1:123@bitcoin-regtest:19001"
      - "BTCEXP_HOST=0.0.0.0"

  explorer2:
    image: msmiley/btc-rpc-explorer
    container_name: bitcoin-explorer-2
    restart: on-failure
    ports:
      - "127.0.0.1:8081:3002"
    environment:
      - "BTCEXP_BITCOIND_URI=bitcoin://admin2:123@bitcoin-regtest:19011"
      - "BTCEXP_HOST=0.0.0.0"
